---
baseURL: https://stac.astrogeology.usgs.gov/docs
title: Astrogeology Analysis Ready Data
canonifyURLs: true
theme: 
  - hugo-cite
  - hugo-geekdoc


pygmentsUseClasses: true
pygmentsCodeFences: true
timeout: 180000
pluralizeListTitles: false

defaultContentLanguage: en

disablePathToLower: true
enableGitInfo: true

enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 9

taxonomies:
  tag: tags

outputs:
  home:
    - HTML
  page:
    - HTML
  section:
    - HTML
  taxonomy:
    - HTML
  term:
    - HTML

security:
  exec:
    allow:
      - "^asciidoctor$"

params:
  geekdocRepo: "https://github.com/DOI-USGS/planetary-ard"
  geekdocEditPath: "/tree/main/"
